POST http://localhost:3001/alerts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZDkzYjhjNTQyODhhNGQyZmFlMjU5NyIsInVzZXJuYW1lIjoianVsaW80IiwiaWF0IjoxNjkxOTU5ODg1LCJleHAiOjE2OTI1NjQ2ODV9.aQYumiajzuNSg-dbKBnUQqQiyrZEjcUuCLcdnTTxHK0

{
  "crypto": "bitcoin",
  "min": 7001,
  "max": 30,
  "time": "1998/04/23"
}
